### PR TITLE
Cleanup pom.xml

### PR DESCRIPTION
**Pull request by darxriggs**
There have been many relicts from the bitbucket-branch-source plugin.
Removing unnecessary dependencies and build steps.
Keeping directly required dependencies under `<depdendencies>`.
Setting versions of transitive dependencies under `<dependencyManagement>` to record dependency upper bounds (maven-enforcer-plugin).

### CODE REVIEW

**Comment by darxriggs** [comment]
I wouldn't change this Jenkins plugin to Gradle. All the Jenkins plugins I have seen so far are using Maven. It's not worth the effort and trouble changing it.

**Comment by darxriggs** [comment]
I think that's my last pull-request.

**Comment by alex-dubrouski** [comment]
This one probably does not require a new release, just a merge.

**Comment by darxriggs** [comment]
If released, the plugin would required much less dependencies. Currently the list is quite long - see https://plugins.jenkins.io/skip-notifications-trait.

**Comment by alex-dubrouski** [comment]
Yeah, I guess it is better to finish it. Thanks for your effort.

**Comment by alex-dubrouski** [comment]
Tested and released, should be available in plugin registry soon

**Pull request merged**
